Add a way to look up which sources specify a certain target
neoforged/AccessTransformers pull request #13
Opened 2024-09-24 23:59 UTC by XFactHD

This PR adds a way to look up which sources specify a certain target. This is intended to be used to provide details when an AT causes a coremod to fail, such as when a failed operated on by the field-to-method transformer is made public.

2024-11-08 04:34 UTC, Shadows-of-Fire commented on src/main/java/net/neoforged/accesstransformer/Target.java
> +    public abstract boolean matches(final String className, final TargetType type, final String targetName);
This abstract method should have a javadoc comment

2024-11-08 04:44 UTC, Shadows-of-Fire approved these changes

2024-11-09 10:08 UTC, Shadows-of-Fire commented
Well now the a test is failing, I'm not sure why though, your latest commit was just doc changes.

Which unfortunately means we have a flaky test, screm.  Not even sure if it's related to these changes

2024-11-09 10:09 UTC, Shadows-of-Fire approved these changes

2024-11-23 17:18 UTC, sciwhiz12 requested changes
It doesn't seem to be a flaky test, but rather somehow the newly-added test weren't ran in the original commit, and did run in the new commit that added docs.

In this case, it looks like the test expects only the filename, but the actual result contains the full path.

2024-12-24 02:29 UTC, sciwhiz12 approved these changes

2024-12-24 02:29 UTC, merged